name: TI 
on:
  workflow_dispatch:
    inputs:
      password1:
        default: "01"
        required: false
        description: tester
jobs:
  ti:
    name: ti
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: dk
        run: echo "${{ secrets.EXAMPLE_SECRET_NAME }}"
